name: debug Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew assembleDebug

      - name: Create Debug Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="debug-${{ github.sha }}"
          TITLE="Debug Build ${{ github.sha }}"
          BODY="auto release from debug-build ${{ github.sha }}"

          gh release create "$TAG" \
            --title "$TITLE" \
            --notes "$BODY" \
            --prerelease \
            --latest=false \
            "app/build/outputs/apk/debug/revanced-manager*.apk"
